# common configuration
common:
  log:
    name: singo
    dir: /Storage/Logs
    level: DEBUG
  debug: 1

# mailer configuration
mailer:
  host: localhost
  port: 25
  username: username
  password: password
  encryption: null
  auth_mode: null

# database & orm configuration
database:
  connection:
    driver: pdo_mysql
    dbname: singo
    user: root
    password: 123
    hostname: localhost
  orm:
    proxy_dir: /Storage/Orm/Proxy
    proxy_namespace: App\Storage\Orm\Proxy
    mappings:
      type: annotation
      namespace: App\Entities
      path: ./src/App/Entities

# JWT configuration
jwt:
  secret_key: keep_me_secret
  life_time: 86400
  options:
    header_name: AUTH-HEADER-TOKEN

# firewall configuration
firewall:
  login:
    pattern: user\/login
    anonymous: yes
  secured:
    pattern: ^.*$
    jwt:
      use_forward: 1
      require_previous_session: 0
      stateless: 1

# modules
modules:
  base_namespace: App\Modules
  modules:
    -
      User:
        controllers:
          - UserController